console.log("hello from typescript (j'ai été compilé !!!)");
var a = 120 * 2;
var b = "hello world";
var c = true && false || true;
var d = [1, 2, 3, 55];
var e = ["a", "b", "c"];
var f = [1, true];
var g = {};
var userAddress = [100, "rue du pot"];
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
